# Automatically generated by SST
import sst

KB = 1024
MB = 1024*KB
GB = 1024*MB

# Define SST Program Options:
sst.setProgramOption("timebase", "1ps")
sst.setProgramOption("stopAtCycle", "0 ns")

# Define the SST Components:
comp_cpu0 = sst.Component("cpu0", "macsimComponent.macsimComponent")
comp_cpu0.addParams({
     "trace_file" : "trace_file_list",
     "mem_size" : 4*GB,
     "command_line" :"--clock_cpu=4.0 --clock_cpu=4.0 --clock_l3=4.0 --clock_noc=4.0 --clock_mc=4.0 " + \
                     "--use_memhierarchy=1 --perfect_icache=1 " + \
                     "--num_sim_cores=1 --num_sim_large_cores=1 --num_sim_small_cores=0 " + \
                     "--core_type=x86",
     "debug_level" : "0",
     "num_link" : "1",
     "frequency" : "4 Ghz",
     "output_dir" : "results",
     "debug" : "0",
     "param_file" : "params.in"
})
comp_core0l1icache = sst.Component("core0l1icache", "memHierarchy.Cache")
comp_core0l1icache.addParams({
     "debug_level" : "8",
     "debug" : "0",
     "access_latency_cycles" : "1",
     "cache_frequency" : "4 Ghz",
     "replacement_policy" : "lru",
     "coherence_protocol" : "MESI",
     "associativity" : "8",
     "cache_line_size" : "128",
     "L1" : "1",
     "cache_size" : "64 KB",
     "mshr_latency_cycles" : "0"
})
comp_core0l1dcache = sst.Component("core0l1dcache", "memHierarchy.Cache")
comp_core0l1dcache.addParams({
     "debug_level" : "8",
     "debug" : "0",
     "access_latency_cycles" : "3",
     "cache_frequency" : "4 Ghz",
     "replacement_policy" : "lru",
     "coherence_protocol" : "MESI",
     "associativity" : "8",
     "cache_line_size" : "128",
     "L1" : "1",
     "cache_size" : "64 KB",
     "mshr_latency_cycles" : "0"
})

link_c0_icache = sst.Link("link_c0_icachec0_icache")
link_c0_icache.connect( (comp_cpu0, "core0-icache", "1000ps"), (comp_core0l1icache, "high_network_0", "1000ps") )
link_c0_dcache = sst.Link("link_c0_dcachec0_dcache")
link_c0_dcache.connect( (comp_cpu0, "core0-dcache", "1000ps"), (comp_core0l1dcache, "high_network_0", "1000ps") )

comp_cpu0l1l2bus = sst.Component("cpu0l1l2bus", "memHierarchy.Bus")
comp_cpu0l1l2bus.addParams({
     "debug" : "0",
     "bus_frequency" : "4 Ghz"
})

link_c0_icache_bus = sst.Link("link_c0_icache_busc0_icache_bus")
link_c0_icache_bus.connect( (comp_core0l1icache, "low_network_0", "10000ps"), (comp_cpu0l1l2bus, "high_network_0", "10000ps") )
link_c0_dcache_bus = sst.Link("link_c0_dcache_busc0_dcache_bus")
link_c0_dcache_bus.connect( (comp_core0l1dcache, "low_network_0", "10000ps"), (comp_cpu0l1l2bus, "high_network_1", "10000ps") )

comp_cpu0l2cache = sst.Component("cpu0l2cache", "memHierarchy.Cache")
comp_cpu0l2cache.addParams({
     "debug_level" : "8",
     "debug" : "0",
     "access_latency_cycles" : "8",
     "cache_frequency" : "4 Ghz",
     "replacement_policy" : "lru",
     "coherence_protocol" : "MESI",
     "associativity" : "8",
     "cache_line_size" : "128",
     "L1" : "0",
     "cache_size" : "512 KB",
     "mshr_latency_cycles" : "0"
})

comp_memory0 = sst.Component("memory0", "memHierarchy.MemController")
comp_memory0.addParams({
     "debug" : "0",
     "coherence_protocol" : "MESI",
     "backend.mem_size" : 4096,
     "clock" : "1 GHz",
     "access_time" : "97 ns",
     "rangeStart" : "0"
})

link_bus_cpu0l2cache = sst.Link("link_bus_cpu0l2cachebus_cpu0l2cache")
link_bus_cpu0l2cache.connect( (comp_cpu0l1l2bus, "low_network_0", "10000ps"), (comp_cpu0l2cache, "high_network_0", "10000ps") )
link_cpu0l2_mem0 = sst.Link("link_cpu0l2_mem0cpu0l2_mem0")
link_cpu0l2_mem0.connect( (comp_cpu0l2cache, "low_network_0", "10000ps"), (comp_memory0, "direct_link", "10000ps") )


# Define the SST Component Statistics Information
# Define SST Statistics Options:
sst.setStatisticLoadLevel(7)
sst.setStatisticOutput("sst.statoutputcsv", {
  "separator" : ",",
  "filepath" : "sst.stat.csv",
  "outputtopheader" : 1,
  "outputsimtime" : 1,
  "outputrank" : 1,
})

# Define Component Statistics Information:
sst.enableAllStatisticsForComponentType("memHierarchy.Cache")
sst.enableAllStatisticsForComponentType("memHierarchy.MemController")
