
all:
	perl knobgen.pl
	perl statgen.pl

install:
	perl knobgen.pl
	perl statgen.pl

dbg:
	perl knobgen.pl
	perl statgen.pl

opt:
	perl knobgen.pl
	perl statgen.pl

gpf:
	perl knobgen.pl
	perl statgen.pl

distclean:
clean:
	rm -rf ../src/*.param.h ../src/*.stat.h ../src/all_knobs.* ../src/all_stats.* ../src/statsEnums.h

clean-local:
	rm -rf ../src/*.param.h ../src/*.stat.h ../src/all_knobs.cc ../src/all_stats.cc ../src/statsEnums.h
