
all:
	./run_interface

install:
	./run_interface

dbg:
	./run_interface

opt:
	./run_interface

gpf:
	./run_interface

clean:
	rm -rf ../src/*.param.h ../src/*.stat.h ../src/all_knobs.* ../src/all_stats.* ../src/*_interface.h ../src/statsEnums.h

clean-local:
	rm -rf ../src/*.param.h ../src/*.stat.h ../src/all_knobs.cc ../src/all_stats.cc ../src/*_interface.h ../src/statsEnums.h
