#!/usr/bin/env python3

#########################################################################################
# Author      : Jaekyu Lee (jq.lee17@gmail.com)
# Description : scons for generating stats/knobs
#########################################################################################

import os

# Build option
Import('flags')

## clean option
if GetOption('clean'):
  os.system('rm -rf ../src/all_knobs.* ../src/all_stats.* ../src/statsEnums.h')
## otherwise generate stats/knobs
else:
  os.system('perl knobgen.pl')
  if flags['pin_3_13_trace'] == '1':
    os.system('perl statgen.pl 1.1')
  else:
    os.system('perl statgen.pl 1.0')

